import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
const dir=mkdtempSync(path.join(tmpdir(),'velorie-test-')),port=3217,base=`http://127.0.0.1:${port}`;
const proc=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:String(port),DATA_DIR:dir,NODE_ENV:'test',ADMIN_EMAIL:'admin@test.pl',ADMIN_PASSWORD:'Testing-admin-Password!',SEED_DEMO:'false'}});
const start=new Promise((resolve,reject)=>{proc.stdout.on('data',resolve);proc.on('error',reject);proc.on('exit',c=>reject(new Error('Server exited '+c)))});
let admin={},seller={},buyer={},outsider={};
async function request(client,url,method='GET',data,expected=200){const r=await fetch(base+url,{method,headers:{'X-Velorie-Request':'1','Content-Type':'application/json',...(client.cookie?{Cookie:client.cookie,'X-CSRF-Token':client.csrf}:{})},...(data?{body:JSON.stringify(data)}:{})});let out=await r.json();assert.equal(r.status,expected,JSON.stringify(out));if(r.headers.get('set-cookie'))client.cookie=r.headers.get('set-cookie').split(';')[0];if(out.csrf)client.csrf=out.csrf;return out}
test('Marketplace: identities, moderation, private downloads, accounting and authorization',async t=>{await start;try{
 await request(admin,'/api/login','POST',{email:'admin@test.pl',password:'Testing-admin-Password!'});
 for(const[c,name]of [[seller,'Seller'],[buyer,'Buyer'],[outsider,'Outsider']])await request(c,'/api/register','POST',{name,email:name+'@test.pl',password:'TestPassword-1234'},201);
 await request(buyer,'/api/admin','GET',null,403);
 await request(seller,'/api/become-seller','POST',{});
 let upload=await fetch(base+'/api/uploads?kind=archive',{method:'POST',headers:{Cookie:seller.cookie,'X-CSRF-Token':seller.csrf,'X-Velorie-Request':'1','X-File-Name':'asset.zip'},body:Buffer.from([80,75,5,6,...Array(18).fill(0)])});assert.equal(upload.status,201);const file=await upload.json();
 const form={title:'Integration product',category:'minecraft-plugins',price:10000,description:'A real test product with enough description.',license:'Test license for one account',version:'1.0',requirements:'Node',tags:'test',file:file.id,status:'pending'};
 let p=await request(seller,'/api/products','POST',form);assert.equal(p.status,'pending');
 await request(buyer,'/api/products/'+p.id,'GET',null,404);
 await request(admin,'/api/admin/products/'+p.id,'PATCH',{status:'published'});
 await request(buyer,'/api/products/'+p.id,'PATCH',form,403);
 await request(buyer,'/api/orders','POST',{products:[p.id],accepted:true},400);
 await request(admin,'/api/admin/settings','PATCH',{salesEnabled:true,legalReady:true,bankOwner:'Test operator',bankAccount:'PL00123456789012345678901234'});
 const o=await request(buyer,'/api/orders','POST',{products:[p.id],accepted:true},201);assert.equal(o.total,10000);assert.equal(o.items[0].net,9000);
 let blocked=await fetch(base+`/download/${o.id}/${p.id}`,{headers:{Cookie:buyer.cookie}});assert.equal(blocked.status,403);
 await request(admin,'/api/admin/orders/'+o.id,'PATCH',{status:'paid'});
 const download=await fetch(base+`/download/${o.id}/${p.id}`,{headers:{Cookie:buyer.cookie}});assert.equal(download.status,200);assert.equal((await download.arrayBuffer()).byteLength,22);
 assert.equal((await fetch(base+`/download/${o.id}/${p.id}`,{headers:{Cookie:outsider.cookie}})).status,403);
 await request(buyer,'/api/orders','POST',{products:[p.id],accepted:true},400);
 await request(buyer,'/api/reviews','POST',{product:p.id,rating:5,body:'Everything works great'});
 await request(outsider,'/api/reviews','POST',{product:p.id,rating:5,body:'Not a buyer'},403);
 const balance=await request(seller,'/api/my');assert.equal(balance.wallet.available,9000);
 const pay=await request(seller,'/api/payouts','POST',{amount:9000,account:'PL00123456789012345678901234',owner:'Seller Test'},201);
 await request(seller,'/api/payouts','POST',{amount:100,account:'PL00123456789012345678901234',owner:'Seller Test'},400);
 await request(admin,'/api/admin/orders/'+o.id,'PATCH',{status:'refunded',confirmed:true});
 await request(admin,'/api/admin/payouts/'+pay.id,'PATCH',{status:'paid'},400);
 await request(admin,'/api/admin/payouts/'+pay.id,'PATCH',{status:'rejected'});
 assert.equal((await fetch(base+`/download/${o.id}/${p.id}`,{headers:{Cookie:buyer.cookie}})).status,403);
 const ticket=await request(buyer,'/api/tickets','POST',{subject:'Support test',body:'Please help with product'},201);
 await request(outsider,'/api/tickets/'+ticket.id,'POST',{body:'Unauthorized'},403);
 await request(admin,'/api/tickets/'+ticket.id,'POST',{body:'We can help',status:'closed'});
 let noCsrf=await fetch(base+'/api/profile',{method:'PATCH',headers:{Cookie:buyer.cookie,'Content-Type':'application/json','X-Velorie-Request':'1'},body:JSON.stringify({name:'Malicious',bio:''})});assert.equal(noCsrf.status,403);
 let badOrigin=await fetch(base+'/api/login',{method:'POST',headers:{Origin:'https://evil.test','X-Velorie-Request':'1'},body:'{}'});assert.equal(badOrigin.status,403);
 let state=await request(admin,'/api/admin');const bu=state.users.find(u=>u.email==='buyer@test.pl');await request(admin,'/api/admin/users/'+bu.id,'PATCH',{blocked:true});await request(buyer,'/api/my','GET',null,401);
 assert.equal(state.orders.length,1);assert.ok(state.audit.length>8);
 }finally{proc.kill('SIGTERM');await new Promise(r=>proc.once('exit',r));rmSync(dir,{recursive:true,force:true})}});
